AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy sns-to-slack lambda function.

Resources:
# Benchmark Function
  snsToSlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Provided
      Runtime: provided
      CodeUri: .build/lambda/SNSToSlack/lambda.zip
# Instructs new versions to be published to an alias named "live".
      AutoPublishAlias: live
